### ISSUE TITLE
NATS / K8s : One broker in a 3 broker Kubernetes cluster does not receive requests

### ISSUE THREAD

**Issue by balamuru** [nats-io/k8s#69] opened 2020-06-12 19:39 UTC
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [X] Included `nats-server -DV` output 
 - [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
nats-server version 2.1.0

#### OS/Container environment:
Kubernetes (see  simple-nats-* yaml attached)

##### Scenario 1
* Use a kubernetes cluster (or create an ephemeral k8s "kind" cluster using the command ``` kind create cluster --config 5-node-cluster.yaml  ```)
* Install a 3 broker NATS cluster into the K8s cluster ``` kubectl apply -f simple-nats-3.yml ```
* Create 3 terminal to observe the log output of each of the pods
  * ```  kubectl logs -f nats-0 ```
  * ```  kubectl logs -f nats-1 ```
  * ```  kubectl logs -f nats-2 ```
* Create a nats-box instance within the cluster to message the clusters ``` kubectl run -i --rm --tty nats-box --image=synadia/nats-box --restart=Never ```
* From within nats-box in teh k8s cluster, attempt to publish to each of the brokers
  * ```nats-pub -s nats-0.nats.default.svc:4222 topic.test "Hello"  ```
  * ```nats-pub -s nats-1.nats.default.svc:4222 topic.test "Hello"  ``` 
  * ```nats-pub -s nats-2.nats.default.svc:4222 topic.test "Hello"  ```

##### Scenario 2
If a 2  broker config is setup instead of a 3 broker config, both nats-0 and nats-1 work (see attachment for 2 broker yaml config)

#### Expected result:
* nats-pub can communicate with all 3 brokers
#### Actual result:
* brokers nats-0 and nats-1 can be reached, but not nats-2
* Lots of communication errors on brokers nats-0 and nats-2
![nats-communication](https://user-images.githubusercontent.com/73320/84540042-39b0bd00-acba-11ea-931f-a1eedd7a8288.PNG)

[config.zip](https://github.com/nats-io/nats-server/files/4772862/config.zip)

## Notes
Slack discussion with @wallyqs captured at https://natsio.slack.com/archives/C9V1869TR/p1591803566033600?thread_ts=1590350719.031900&cid=C9V1869TR

**Comment by balamuru** [comment] 2020-06-13 01:32
Tried this by modifying the simple-nats yaml script to generate 4  broker  replicas . It seems like 3 work with nats-2 being the unresponsive broker to nats-box publish requests

**Comment by balamuru** [comment] 2020-06-25 19:56
A team-member found this: ...

This is actually a Kubernetes issue. The symptom is that when accessing nodePort from inside cluster, either from host or from pod, it fails intermittently. Precisely, if the nodePort is routed to the same node as the requester, it's successful, otherwise, it fails.
 
The cause is due to some iptables changes in kubernetes exposed a kernel bug not fixed in RHEL7 about UDP cksum offloading.
  The issue: https://github.com/kubernetes/kubernetes/issues/88986
  The fix: https://github.com/kubernetes/kubernetes/pull/92035 (it's committed last week, so don't know which version of kubernetes will have it.)
 
One workaround is:
sudo iptables -A OUTPUT -p udp -m udp --dport 8472 -j MARK --set-xmark 0x0
on all the nodes in the cluster.

**Comment by wallyqs** [comment] 2020-06-25 20:20
Amazing 🤯 , thanks for sharing @balamuru

**Comment by wallyqs** [comment] 2020-07-18 01:20
Closing since root cause found.

**Closed by wallyqs** 2020-07-18 01:20 UTC
