### ISSUE TITLE
[nats]: service type

### ISSUE THREAD

**Issue by crazymushrooms** [nats-io/k8s#687] opened 2023-03-13 11:07 UTC
Currently the helm chart doesn't support the configuration of `type` and provides just the `ClusterIP`type.
It would be great to make it configurable through the values.

for example:

```
Subject: [PATCH] 
---
Index: helm/charts/nats/templates/service.yaml
======================================================
diff --git a/helm/charts/nats/templates/service.yaml b/helm/charts/nats/templates/service.yaml
--- a/helm/charts/nats/templates/service.yaml	(revision 02a2d96ff67e2c8c81aedaa4b04cca3d12a5514d)
+++ b/helm/charts/nats/templates/service.yaml	(date 1678705386336)
@@ -14,7 +14,10 @@
 spec:
   selector:
     {{- include "nats.selectorLabels" . | nindent 4 }}
+  type: {{ .Values.serviceType | default "ClusterIP" }}
+  {{- if or (eq .Values.serviceType "ClusterIP") (eq .Values.serviceType "") }}
   clusterIP: None
+  {{- end }}
   publishNotReadyAddresses: true
   {{- if .Values.topologyKeys }}
   topologyKeys:

Index: helm/charts/nats/values.yaml
===================================================================
diff --git a/helm/charts/nats/values.yaml b/helm/charts/nats/values.yaml
--- a/helm/charts/nats/values.yaml	(revision 02a2d96ff67e2c8c81aedaa4b04cca3d12a5514d)
+++ b/helm/charts/nats/values.yaml	(date 1678705463167)
@@ -414,6 +414,9 @@
 # Annotations to add to the NATS Service
 serviceAnnotations: {}
 
+# Service type
+serviceType: "ClusterIP"
+
 # additionalContainers are the sidecar containers to add to the NATS StatefulSet
 additionalContainers: []
 
```

**Comment by caleblloyd** [comment] 2023-03-13 13:29
Duplicate of #580

**Closed by caleblloyd** 2023-03-13 13:29 UTC
